# Generated by Django 6.1.2 on 2026-10-07 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChoiceSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(max_length=3)),
            ],
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_1',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_10',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_11',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_12',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_13',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_14',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_15',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_16',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_2',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_3',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_4',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_5',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_6',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_7',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_8',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_9',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_9_boolean',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_9_other',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_9_other_boolean',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_9_other_proportion',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_9_other_time',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_9_proportion',
        ),
        migrations.RemoveField(
            model_name='questionnaire',
            name='question_9_time',
        ),
        migrations.AlterField(
            model_name='questionnaire',
            name='sex',
            field=models.CharField(max_length=10),
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=5)),
                ('label', models.CharField(max_length=255)),
                ('order', models.PositiveIntegerField(default=0)),
                ('choice_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='questionnaire.choiceset')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('required', models.BooleanField(default=False)),
                ('choice_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='questionnaire.choiceset')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questionnaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='questionnaire.questionnaire')),
                ('choice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questionnaire.choice')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='questionnaire.question')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('questionnaire', 'question'), name='unique_questionnaire_question')],
            },
        ),
    ]
