# Generated by Django 6.1.2 on 2026-10-07 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaire', '0002_choiceset_remove_questionnaire_question_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='value',
            field=models.CharField(max_length=100),
        ),
    ]
