# Generated by Django 5.2.3 on 2025-09-01 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_2', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Às vezes'), (4, 'Frequentemente'), (5, 'Sempre')], verbose_name='No trabalho, eu fico sentado:')),
                ('question_3', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Às vezes'), (4, 'Frequentemente'), (5, 'Sempre')], verbose_name='No trabalho, eu fico em pé')),
                ('question_4', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Às vezes'), (4, 'Frequentemente'), (5, 'Sempre')], verbose_name='No trabalho, eu ando:')),
                ('question_5', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Às vezes'), (4, 'Frequentemente'), (5, 'Sempre')], verbose_name='No trabalho, eu levanto objetos pesados:')),
                ('question_6', models.IntegerField(choices=[(1, 'Muito frequentemente'), (2, 'Frequentemente'), (3, 'Às vezes'), (4, 'Raramente'), (5, 'Nunca')], verbose_name='Depois do trabalho, eu me sinto cansado:')),
                ('question_7', models.IntegerField(choices=[(1, 'Muito frequentemente'), (2, 'Frequentemente'), (3, 'Às vezes'), (4, 'Raramente'), (5, 'Nunca')], verbose_name='No trabalho, eu suo:')),
                ('question_8', models.IntegerField(choices=[(5, 'Muito mais pesado'), (4, 'Mais pesado'), (3, 'Iguamente pesado'), (2, 'Mais leve'), (1, 'Muito mais leve')], verbose_name='Em comparação com o trabalho de outras pessoas da minha idade, o meu trabalho é fisicamente:')),
                ('question_10', models.IntegerField(choices=[(5, 'Muito maior'), (4, 'Maior'), (3, 'Igual'), (2, 'Mais leve'), (1, 'Muito mais leve')], verbose_name='Em comparação com outras pessoas da minha idade, minha atividade física durante os momentos de lazer é:')),
                ('question_11', models.IntegerField(choices=[(1, 'Muito frequentemente'), (2, 'Frequentemente'), (3, 'Às vezes'), (4, 'Raramente'), (5, 'Nunca')], verbose_name='Durante os momentos de lazer eu suo:')),
                ('question_12', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Às vezes'), (4, 'Frequentemente'), (5, 'Sempre')], verbose_name='Durante os momentos de lazer, eu pratico atividades físicas:')),
                ('question_13', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Às vezes'), (4, 'Frequentemente'), (5, 'Sempre')], verbose_name='Durante os momentos de lazer, eu assisto televisão:')),
                ('question_14', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Às vezes'), (4, 'Frequentemente'), (5, 'Sempre')], verbose_name='Durante os momentos de lazer, eu ando:')),
                ('question_15', models.IntegerField(choices=[(1, 'Nunca'), (2, 'Raramente'), (3, 'Às vezes'), (4, 'Frequentemente'), (5, 'Sempre')], verbose_name='Durante os momentos de lazer, eu ando de bicicleta:')),
            ],
        ),
    ]
